// framework-packages/ui-library-react/index.js
import React, { forwardRef, useEffect } from 'react';
import { defineCustomElements as defineElements } from 'ui-library/loader';

// Initialize web components
let componentsInitialized = false;
const initializeComponents = () => {
  if (!componentsInitialized) {
    defineElements();
    componentsInitialized = true;
  }
};

// Helper function to convert React props to web component attributes
const convertProps = (props) => {
  const webComponentProps = { ...props };
  
  // Convert boolean props to string attributes for web components
  if (typeof webComponentProps.loading === 'boolean') {
    webComponentProps.loading = webComponentProps.loading ? 'true' : undefined;
  }
  if (typeof webComponentProps.disabled === 'boolean') {
    webComponentProps.disabled = webComponentProps.disabled ? 'true' : undefined;
  }
  if (typeof webComponentProps.required === 'boolean') {
    webComponentProps.required = webComponentProps.required ? 'true' : undefined;
  }
  if (typeof webComponentProps.error === 'boolean') {
    webComponentProps.error = webComponentProps.error ? 'true' : undefined;
  }

  return webComponentProps;
};

// React wrapper components
export const UiButton = forwardRef((props, ref) => {
  useEffect(() => {
    initializeComponents();
  }, []);

  const webComponentProps = convertProps(props);
  return React.createElement('ui-button', { ...webComponentProps, ref }, props.children);
});

export const UiCard = forwardRef((props, ref) => {
  useEffect(() => {
    initializeComponents();
  }, []);

  const webComponentProps = convertProps(props);
  return React.createElement('ui-card', { ...webComponentProps, ref }, props.children);
});

export const UiCardHeader = forwardRef((props, ref) => {
  useEffect(() => {
    initializeComponents();
  }, []);

  const webComponentProps = convertProps(props);
  return React.createElement('ui-card-header', { ...webComponentProps, ref }, props.children);
});

export const UiCardTitle = forwardRef((props, ref) => {
  useEffect(() => {
    initializeComponents();
  }, []);

  const webComponentProps = convertProps(props);
  return React.createElement('ui-card-title', { ...webComponentProps, ref }, props.children);
});

export const UiCardContent = forwardRef((props, ref) => {
  useEffect(() => {
    initializeComponents();
  }, []);

  const webComponentProps = convertProps(props);
  return React.createElement('ui-card-content', { ...webComponentProps, ref }, props.children);
});

export const UiInput = forwardRef((props, ref) => {
  useEffect(() => {
    initializeComponents();
  }, []);

  const webComponentProps = convertProps(props);
  return React.createElement('ui-input', { ...webComponentProps, ref });
});

// Export the initialize function
export const defineCustomElements = () => {
  initializeComponents();
};

UiButton.displayName = 'UiButton';
UiCard.displayName = 'UiCard';
UiCardHeader.displayName = 'UiCardHeader';
UiCardTitle.displayName = 'UiCardTitle';
UiCardContent.displayName = 'UiCardContent';
UiInput.displayName = 'UiInput';

// framework-packages/ui-library-angular/index.js
import { Component, Input, Output, EventEmitter, NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { defineCustomElements as defineElements } from 'ui-library/loader';

// Initialize web components
let componentsInitialized = false;
const initializeComponents = () => {
  if (!componentsInitialized) {
    defineElements();
    componentsInitialized = true;
  }
};

// Angular wrapper components
@Component({
  selector: 'ui-button',
  template: `
    <ui-button 
      [attr.variant]="variant"
      [attr.size]="size"
      [attr.loading]="loading"
      [attr.disabled]="disabled"
      (click)="$event">
      <ng-content></ng-content>
    </ui-button>
  `
})
export class UiButtonComponent {
  @Input() variant;
  @Input() size;
  @Input() loading;
  @Input() disabled;

  constructor() {
    initializeComponents();
  }
}

@Component({
  selector: 'ui-card',
  template: `<ui-card><ng-content></ng-content></ui-card>`
})
export class UiCardComponent {
  constructor() {
    initializeComponents();
  }
}

@Component({
  selector: 'ui-card-header',
  template: `<ui-card-header><ng-content></ng-content></ui-card-header>`
})
export class UiCardHeaderComponent {
  constructor() {
    initializeComponents();
  }
}

@Component({
  selector: 'ui-card-title',
  template: `<ui-card-title><ng-content></ng-content></ui-card-title>`
})
export class UiCardTitleComponent {
  constructor() {
    initializeComponents();
  }
}

@Component({
  selector: 'ui-card-content',
  template: `<ui-card-content><ng-content></ng-content></ui-card-content>`
})
export class UiCardContentComponent {
  constructor() {
    initializeComponents();
  }
}

@Component({
  selector: 'ui-input',
  template: `
    <ui-input
      [attr.label]="label"
      [attr.placeholder]="placeholder"
      [attr.value]="value"
      [attr.required]="required"
      [attr.error]="error"
      [attr.error-message]="errorMessage"
      (uiInput)="uiInput.emit($event.detail)"
      (uiBlur)="uiBlur.emit()"
      (uiFocus)="uiFocus.emit()">
    </ui-input>
  `
})
export class UiInputComponent {
  @Input() label;
  @Input() placeholder;
  @Input() value;
  @Input() required;
  @Input() error;
  @Input() errorMessage;
  
  @Output() uiInput = new EventEmitter();
  @Output() uiBlur = new EventEmitter();
  @Output() uiFocus = new EventEmitter();

  constructor() {
    initializeComponents();
  }
}

@NgModule({
  declarations: [
    UiButtonComponent,
    UiCardComponent,
    UiCardHeaderComponent,
    UiCardTitleComponent,
    UiCardContentComponent,
    UiInputComponent
  ],
  imports: [CommonModule],
  exports: [
    UiButtonComponent,
    UiCardComponent,
    UiCardHeaderComponent,
    UiCardTitleComponent,
    UiCardContentComponent,
    UiInputComponent
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class UiLibraryModule {}

// Export the initialize function
export const defineCustomElements = () => {
  initializeComponents();
};
